name: Medicall
description: Telemedicine for everyone.

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  firebase_auth: ^0.8.4+5
  intl: "^0.15.2"
  bubble_tab_indicator: "^0.1.4"
  google_sign_in: ^4.0.1+1
  http: ^0.12.0
  flutter_auth_buttons: ^0.3.1
  graphql_flutter: ^0.9.5
  multi_image_picker: ^4.0.3
  google_maps_flutter: ^0.0.3
  flutter_google_places: ^0.1.4
  location: ^1.4.1
  flutter_form_builder: ^2.1.0
  flutter_alert: ^0.4.0
  fluttertoast: ^3.0.3
  country_pickers: ^1.0.4
  localstorage: ^1.1.0
  json_serializable: ^2.2.1
  firebase_messaging: ^4.0.0+4
  oktoast: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  image_path: "assets/icon/logo_image.png"
  adaptive_icon_background: "assets/icon/logo_back.png"
  adaptive_icon_foreground: "assets/icon/logo_fore.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true
  fonts:
    - family:  MedicallApp
      fonts:
        - asset: assets/fonts/MedicallApp.ttf
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icon/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/
  
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
