name: Medicall
description: Telemedicine for everyone.

version: 1.0.2+1

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  #firebase
  #firebase_core: ^0.4.0+8
  firebase_auth: ^0.14.0
  cloud_firestore: ^0.12.9
  firebase_messaging: ^5.1.2
  cloud_functions: ^0.4.1
  firebase_analytics: ^4.0.2
  firebase_storage: ^3.0.4
  flutter_crashlytics: ^1.0.0
  #google
  google_sign_in: ^4.0.6
  google_maps_flutter: ^0.5.20+6
  flutter_google_places: ^0.2.3
  #utils
  cupertino_icons: ^0.1.0
  url_launcher: ^5.0.2
  location: ^2.3.5
  intl: ^0.15.2
  http: ^0.12.0
  stripe_payment: ^0.1.1
  json_serializable: ^2.2.1
  shared_preferences: ^0.5.3+1
  keyboard_visibility: ^0.5.6
  #bubble_tab_indicator: ^0.1.4
  flutter_auth_buttons: ^0.3.1
  flutter_form_builder: ^3.4.1
  #camera/images
  multi_image_picker: ^4.5.2
  carousel_pro: ^1.0.0
  cached_network_image: ^1.1.0
  #notifications
  flutter_alert: ^0.4.0
  oktoast: ^2.1.7
  fluttertoast: ^3.1.0
  image_picker: ^0.6.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.5.1
  image: ^2.0.7
  flutter_launcher_icons: ^0.7.2
  screenshots:
  intl_translation: ^0.17.2
  flutter_driver:
    sdk: flutter

flutter_icons:
  image_path_android: 'assets/icon/logo_image.png'
  image_path_ios: 'assets/icon/logo_image.png'
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: 'assets/icon/logo_back.png' # only available for Android 8.0 devices and above
  adaptive_icon_foreground: 'assets/icon/logo_fore.png' # only available for Android 8.0 devices and above

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true
  fonts:
    - family: MedicallApp
      fonts:
        - asset: assets/fonts/MedicallApp.ttf
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icon/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
