name: Medicall
description: Telemedicine for everyone.

version: 1.0.2+1

environment:
  sdk: ">=2.8.0 <3.0.0"
https://github:
  com/FirebaseExtended/flutterfire/commit/3fc3ca8e8f2f2577b1553e3513a7dba45da31b37:
dependencies:
  flutter:
    sdk: flutter
  #firebase
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  firebase_messaging: ^7.0.0
  cloud_functions: ^0.6.0
  firebase_storage: ^4.0.0
  firebase_analytics: ^6.0.0
  flutter_crashlytics: ^1.0.0
  #apple
  apple_sign_in: ^0.1.0
  #google
  google_sign_in: ^4.1.4
  #google_maps_flutter: ^0.5.21+15
  flutter_google_places: ^0.2.4
  #stripe
  stripe_payment: ^1.0.7
  #utils
  flutter_screenutil: ^1.0.2
  flutter_absolute_path: ^1.0.6
  cupertino_icons: ^0.1.0
  url_launcher: ^5.4.2
  flutter_linkify: ^2.1.0
  location: ^2.3.5
  http: ^0.12.0
  flutter_datetime_picker: ^1.3.8
  json_serializable: ^3.3.0
  flutter_auth_buttons: ^0.3.1
  flutter_form_builder: '3.6.0'
  flutter_typeahead: ^1.7.0
  fading_edge_scrollview: ^1.1.4
  #camera/images
  camera: ^0.5.8+2
  video_player: ^0.10.11+1
  dots_indicator: ^1.0.0
  extended_image: ^0.8.0
  #image_picker: ^0.6.3+1
  multi_image_picker: ^4.7.12
  image_picker: ^0.6.6+1
  #notifications
  flushbar: ^1.10.4
  #flutter_alert: ^0.4.0
  #chat
  dash_chat: ^1.0.15
  #state_management
  provider: ^4.0.2
  #animation
  flare_splash_screen: ^3.0.0
  simple_animations: ^1.3.12
  mask_text_input_formatter: ^1.0.6
  uuid: ^2.0.4
  fluri: ^1.2.8
  super_rich_text: ^0.2.1
  property_change_notifier: ^0.2.0
  enum_to_string: ^1.0.9
  datetime_picker_formfield: ^1.0.0
  photo_view: ^0.10.1
  step_progress_indicator: ^0.2.3+6
  auto_size_text: ^2.1.0
  rounded_loading_button: ^1.0.0
  cached_network_image: ^2.2.0+1
  stream_chat_flutter: ^0.2.4
  get_version: ^0.2.2
  native_updater: ^0.0.3
  version: ^1.2.0

dependency_overrides:
  intl: ^0.16.1
  flutter_chips_input: ^1.9.0-dev.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  image: ^2.0.7
  flutter_launcher_icons: ^0.7.2
  screenshots:
  intl_translation: ^0.17.10
  flutter_driver:
    sdk: flutter

flutter_icons:
  image_path_android: 'assets/icon/logo_image.png'
  image_path_ios: 'assets/icon/logo_image.png'
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: 'assets/icon/logo_back.png' # only available for Android 8.0 devices and above
  adaptive_icon_foreground: 'assets/icon/logo_fore.png' # only available for Android 8.0 devices and above

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Light.ttf
        - asset: fonts/Inter-SemiBold.ttf
        - asset: fonts/Inter-Thin.ttf
        - asset: fonts/Inter-Bold.ttf
    - family: MedicallIcons
      fonts:
        - asset: fonts/MedicallIcons.ttf
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icon/
    - assets/icon/cards/
    - assets/splash.flr
    - assets/logout.flr
    - assets/headerlogo.flr
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
