name: Medicall
description: Telemedicine for everyone.

version: 1.0.2+1

environment:
  sdk: '>=2.6.0 <3.0.0'
https://github:
  com/FirebaseExtended/flutterfire/commit/3fc3ca8e8f2f2577b1553e3513a7dba45da31b37:
dependencies:
  flutter:
    sdk: flutter
  #firebase
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  firebase_messaging: ^6.0.15
  cloud_functions: ^0.4.2+3
  firebase_storage: ^3.1.5
  firebase_analytics: ^5.0.11
  flutter_crashlytics: ^1.0.0
  #apple
  apple_sign_in: ^0.1.0
  #google
  google_sign_in: ^4.1.4
  #google_maps_flutter: ^0.5.21+15
  flutter_google_places: ^0.2.4
  #stripe
  stripe_payment: ^1.0.7
  #utils
  flutter_screenutil: ^1.0.2
  cupertino_icons: ^0.1.0
  url_launcher: ^5.4.2
  flutter_linkify: ^2.1.0
  location: ^2.3.5
  http: ^0.12.0
  flutter_datetime_picker: ^1.3.8
  json_serializable: ^2.2.1
  flutter_auth_buttons: ^0.3.1
  flutter_form_builder: '3.6.0'
  flutter_typeahead: ^1.7.0
  #camera/images
  dots_indicator: ^1.0.0
  extended_image: ^0.8.0
  #image_picker: ^0.6.3+1
  multi_image_picker: ^4.6.7
  image_picker: ^0.6.6+1
  #notifications
  flushbar: ^1.10.4
  #flutter_alert: ^0.4.0
  #chat
  dash_chat: ^1.0.15
  #state_management
  provider: ^4.0.2
  #animation
  flare_splash_screen: ^3.0.0
  simple_animations: ^2.2.1
  mask_text_input_formatter: ^1.0.6
  uuid: ^2.0.4
  fluri: ^1.2.8
  stripe_sdk: ^2.8.2

dependency_overrides:
  intl: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.5.1
  image: ^2.0.7
  flutter_launcher_icons: ^0.7.2
  screenshots:
  intl_translation: ^0.17.2
  flutter_driver:
    sdk: flutter

flutter_icons:
  image_path_android: 'assets/icon/logo_image.png'
  image_path_ios: 'assets/icon/logo_image.png'
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: 'assets/icon/logo_back.png' # only available for Android 8.0 devices and above
  adaptive_icon_foreground: 'assets/icon/logo_fore.png' # only available for Android 8.0 devices and above

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true
  fonts:
    - family: MedicallApp
      fonts:
        - asset: assets/fonts/MedicallApp.ttf
    - family: MedicallIcons
      fonts:
        - asset: assets/fonts/MedicallIcons.ttf
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icon/
    - splash.flr
    - logout.flr
    - headerlogo.flr
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
